linters:
  enable:
    - govet
    - errcheck
    - ineffassign
    - staticcheck
    - unused
    - gosimple
    - goconst
    - typecheck
    - gosec
    - depguard
    - gofmt

output:
  formats:
    - format: colored-line-number
  sort-results: true