version: 2

before:
  hooks:
    - go mod tidy
    - go generate ./...
    - go fmt ./...
    - go test ./...

builds:
  - skip: true

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
