input:
  spicedb_watch:
    endpoint: localhost:50051
    cache: "spicedb_cache"

buffer:
  none: {}

pipeline:
  threads: -1
  processors: []

output:
  kafka:
    addresses:
      - localhost:9092
    topic: spicypanda

input_resources: []
processor_resources: []
output_resources: []
cache_resources:
  - label: "spicedb_cache"
    redis:
      url: redis://:6379

rate_limit_resources: []

logger:
  level: INFO
  format: logfmt
  add_timestamp: true
  level_name: level
  timestamp_name: time
  message_name: msg
  static_fields:
    '@service': redpanda-connect
    '@env': development
    '@namespace': default
  file:
    path: ""
    rotate: false
    rotate_max_age_days: 0

metrics:
  prometheus: {}
  mapping: ""

tracer:
  none: {}

shutdown_delay: 0s
shutdown_timeout: 20s
tests: []

redpanda:
  seed_brokers: []
  client_id: benthos
  tls:
    enabled: false
    skip_cert_verify: false
    enable_renegotiation: false
    root_cas: ""
    root_cas_file: ""
    client_certs: []
  sasl: []
  metadata_max_age: 5m
  pipeline_id: ""
  logs_topic: ""
  logs_level: info
  status_topic: ""
  idempotent_write: true
  timeout: 10s
  max_message_bytes: 1MB
  broker_write_max_bytes: 100MB