// Code generated by mockery. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Project is an autogenerated mock type for the Project type
type Project struct {
	mock.Mock
}

type Project_Expecter struct {
	mock *mock.Mock
}

func (_m *Project) EXPECT() *Project_Expecter {
	return &Project_Expecter{mock: &_m.Mock}
}

// Get provides a mock function with given fields:
func (_m *Project) Get() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// Project_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type Project_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
func (_e *Project_Expecter) Get() *Project_Get_Call {
	return &Project_Get_Call{Call: _e.mock.On("Get")}
}

func (_c *Project_Get_Call) Run(run func()) *Project_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Project_Get_Call) Return(_a0 string) *Project_Get_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Project_Get_Call) RunAndReturn(run func() string) *Project_Get_Call {
	_c.Call.Return(run)
	return _c
}

// NewProject creates a new instance of Project. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewProject(t interface {
	mock.TestingT
	Cleanup(func())
}) *Project {
	mock := &Project{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
